import React, { useState } from "react";
import ErrorComp from "../ErrorComp";
import { IoIosArrowDropdown } from "react-icons/io";
import { IoIosCloseCircleOutline } from "react-icons/io";
export default function SelectFile() {
    const [lang, setLang] = useState("Select a language");
    const [error, setError] = useState("");
    const [showList, setShowList] = useState(false);
    const allLangs = ["Abkhazian",
        "Acehnese",
        "Acoli",
        "Afar",
        "Afrikaans",
        "Akan",
        "Albanian",
        "Alur",
        "Amharic",
        "Arabic",
        "Armenian",
        "Assamese",
        "Avaric",
        "Awadhi",
        "Aymara",
        "Azerbaijani",
        "Balinese",
        "Baluchi",
        "Bambara",
        "Bangla",
        "Baoulé",
        "Bashkir",
        "Basque",
        "Batak Karo",
        "Batak Simalungun",
        "Batak Toba",
        "Belarusian",
        "Bemba",
        "Betawi",
        "Bhojpuri",
        "Bikol",
        "Bosnian",
        "Breton",
        "Bulgarian",
        "Buriat",
        "Burmese",
        "Cantonese",
        "Catalan",
        "Cebuano",
        "Central Kurdish",
        "Chamorro",
        "Chechen",
        "Chiga",
        "Chinese (Simplified)",
        "Chinese (Traditional)",
        "Chuukese",
        "Chuvash",
        "Corsican",
        "Crimean Tatar",
        "Croatian",
        "Czech",
        "Danish",
        "Dari",
        "Dinka",
        "Divehi",
        "Dogri",
        "Dombe",
        "Dutch",
        "Dyula",
        "Dzongkha",
        "English",
        "Esperanto",
        "Estonian",
        "Ewe",
        "Faroese",
        "Fijian",
        "Filipino",
        "Finnish",
        "Fon",
        "French",
        "Friulian",
        "Fulani",
        "Ga",
        "Galician",
        "Ganda",
        "Georgian",
        "German",
        "Goan Konkani",
        "Greek",
        "Guarani",
        "Gujarati",
        "Haitian Creole",
        "Hakha Chin",
        "Hausa",
        "Hawaiian",
        "Hebrew",
        "Hiligaynon",
        "Hindi",
        "Hmong",
        "Hungarian",
        "Hunsrik",
        "Iban",
        "Icelandic",
        "Igbo",
        "Iloko",
        "Indonesian",
        "Irish",
        "Italian",
        "Jamaican Patois",
        "Japanese",
        "Javanese",
        "Jingpo",
        "Kalaallisut",
        "Kannada",
        "Kanuri",
        "Kazakh",
        "Khasi",
        "Khmer",
        "Kinyarwanda",
        "Kituba",
        "Kokborok",
        "Komi",
        "Kongo",
        "Korean",
        "Krio",
        "Kurdish",
        "Kyrgyz",
        "Lao",
        "Latgalian",
        "Latin",
        "Latvian",
        "Ligurian",
        "Limburgish",
        "Lingala",
        "Lithuanian",
        "Lombard",
        "Luo",
        "Luxembourgish",
        "Macedonian",
        "Madurese",
        "Maithili",
        "Makasar",
        "Malagasy",
        "Malay",
        "Malay (Arabic)",
        "Malayalam",
        "Maltese",
        "Mam",
        "Manipuri (Meitei Mayek)",
        "Manx",
        "Marathi",
        "Marshallese",
        "Marwari",
        "Meadow Mari",
        "Minangkabau",
        "Mizo",
        "Mongolian",
        "Morisyen",
        "Māori",
        "Nahuatl (Eastern Huasteca)",
        "Ndau",
        "Nepalbhasa (Newari)",
        "Nepali",
        "Nko",
        "Northern Sami",
        "Northern Sotho",
        "Norwegian",
        "Nuer",
        "Nyanja",
        "Occitan",
        "Odia",
        "Oromo",
        "Ossetic",
        "Pampanga",
        "Pangasinan",
        "Papiamento",
        "Pashto",
        "Persian",
        "Polish",
        "Portuguese",
        "Portuguese (Portugal)",
        "Punjabi",
        "Punjabi (Arabic)",
        "Q'eqchi'",
        "Quechua",
        "Romanian",
        "Romany",
        "Rundi",
        "Russian",
        "Samoan",
        "Sango",
        "Sanskrit",
        "Santali (Latin)",
        "Scottish Gaelic",
        "Serbian",
        "Seselwa Creole French",
        "Shan",
        "Shona",
        "Sicilian",
        "Silesian",
        "Sindhi",
        "Sinhala",
        "Slovak",
        "Slovenian",
        "Somali",
        "South Ndebele",
        "Southern Sotho",
        "Spanish",
        "Sundanese",
        "Susu",
        "Swahili",
        "Swati",
        "Swedish",
        "Tahitian",
        "Tajik",
        "Tamazight",
        "Tamazight (Tifinagh)",
        "Tamil",
        "Tatar",
        "Telugu",
        "Tetum",
        "Thai",
        "Tibetan",
        "Tigrinya",
        "Tiv",
        "Tok Pisin",
        "Tongan",
        "Tsonga",
        "Tswana",
        "Tulu",
        "Tumbuka",
        "Turkish",
        "Turkmen",
        "Tuvinian",
        "Udmurt",
        "Ukrainian",
        "Urdu",
        "Uyghur",
        "Uzbek",
        "Venda",
        "Venetian",
        "Vietnamese",
        "Waray",
        "Welsh",
        "Western Frisian",
        "Wolof",
        "Xhosa",
        "Yakut",
        "Yiddish",
        "Yoruba",
        "Yucatec Maya",
        "Zapotec",
        "Zulu",
        "alaallisut",
        "annada",
        "anuri",
        "aroese",
        "azakh",
        "hasi",
        "hmer",
        "ijian",
        "ilipino",
        "innish",
        "inyarwanda",
        "ituba",
        "okborok",
        "omi",
        "on",
        "ongo",
        "orean",
        "rench",
        "rio",
        "riulian",
        "ulani",
        "urdish",
        "yrgyz"];
    const [filteredList, setFilteredList] = useState(allLangs);
    return (
        <div className="relative">
            <div className="border-2 border-black border-opacity-55 w-fit gap-4 flex items-center cursor-pointer hover:bg-black hover:bg-opacity-10" onClick={() => {
                setShowList(!showList);
            }}>
                {lang}
                <IoIosArrowDropdown />
            </div>
            {showList && <div className="shadow-lg shadow-black absolute top-0 bg-white rounded-2xl p-2 " >
                <input type="text" name="search" id="" placeholder="Search..." onChange={(event) => {
                    setFilteredList(allLangs.filter((i) => {
                        return i.toLowerCase().includes(event.target.value.toLowerCase());
                    }))
                }} className="outline-none py-1 px-2  text-gray-800" onFocus={() => {
                    setShowList(true);
                }} />
                <button className="absolute top-2 right-4 hover:bg-gray-300 rounded-full p-1 " onClick={() => {
                    setShowList(false);
                    setFilteredList(allLangs);
                }}><IoIosCloseCircleOutline size={"2rem"} /></button>
                <ul className="h-48 overflow-auto px-4">
                    {
                        filteredList.map((i, index) => (
                            <li key={index} className="cursor-pointer hover:underline" onClick={() => {
                                setLang(i);
                                setShowList(false);
                                setFilteredList(allLangs);
                            }}>{i}</li>
                        ))
                    }
                </ul>
            </div>}
            
            <ErrorComp message={error} design={"text-base"} />
        </div>
    )
}